
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "../globals.css";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  //here we can check the session/auth/whatever and redirect if not valid

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header */}
        <header className="sticky top-0 z-50 w-full bg-black shadow-lg shadow-green-950">
          <div className="flex items-center justify-between p-6 md:p-5">
            {/* Logo */}
            <Link href="/">
            <svg className=" inline fill-none size-14 stroke-green-500 stroke-1"
            fill="#000000" height="200px" width="200px" version="1.1" id="Icons" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" xmlSpace="preserve">
              <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
              <g id="SVGRepo_tracerCarrier" strokeLinecap="round" strokeLinejoin="round"></g>
              <g id="SVGRepo_iconCarrier"> 
              <path d="M26.5,20c-0.8,0-1.5,0.3-2.1,0.7l-2.2-1.5c0.5-0.9,0.8-2,0.8-3.1c0-1.1-0.3-2.1-0.7-3l1.1-0.7c0.6,0.4,1.3,0.7,2.1,0.7 c1.9,0,3.5-1.6,3.5-3.5S27.4,6,25.5,6S22,7.6,22,9.5c0,0.4,0.1,0.8,0.2,1.2l-1,0.7C19.9,9.9,18.1,9,16,9c-1.6,0-3,0.5-4.2,1.4 L8.6,7.2C8.8,6.7,9,6.1,9,5.5C9,3.6,7.4,2,5.5,2S2,3.6,2,5.5S3.6,9,5.5,9c0.6,0,1.2-0.2,1.7-0.4l3.2,3.2C9.5,13,9,14.4,9,16 c0,1.8,0.7,3.5,1.9,4.8l-2,2.5C8.5,23.1,8,23,7.5,23C5.6,23,4,24.6,4,26.5S5.6,30,7.5,30s3.5-1.6,3.5-3.5c0-0.7-0.2-1.4-0.6-1.9 l2-2.5c1,0.6,2.2,1,3.5,1c2,0,3.8-0.9,5.1-2.2l2.1,1.5c-0.1,0.4-0.2,0.8-0.2,1.2c0,1.9,1.6,3.5,3.5,3.5s3.5-1.6,3.5-3.5 S28.4,20,26.5,20z">
              </path> 
              </g>
            </svg>
            <p className=" inline mx-5 text-2xl font-mono align-middle ">Decentralized Storage Network</p>
            </Link>

            {/* Navigation */}
            <nav className="hidden md:flex gap-15 mr-10">
              <Link href="/history" className="hover:text-green-400 transition">
                History
              </Link>
              <Link href="/help" className="hover:text-green-400 transition">
                Help
              </Link>
              <Link href="/profile" className="hover:text-green-400 transition">
                Profile
              </Link>
            </nav>
          </div>
        </header>

        {/* Main content */}
        <main className="m-5 md:m-10 lg:m-20">
          {children}
        </main>

        {/* Footer */}
        <footer className=" dark:bg-[#0a0a0a]">
            Lorem ipsum
        </footer>
      </body>
    </html>
  );
}
